server:
  port: 8888

spring:
  #thymeleaf 配置
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    cache: false #关闭缓存，便于调试

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miaosha?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 1000
      initial-size: 100
      max-wait: 60000
      min-idle: 500

#mybatis配置
mybatis:
  type-aliases-package: io.imwj.miaosha.domain       # 所有Entity别名类所在包
  mapper-locations:
    - classpath:io/imwj/miaosha/dao/*.xml                       # mapper映射文件
  configuration:
    map-underscore-to-camel-case: true

# 打印sql语句 io.imwj.springcloud是包名
logging:
  level:
    io.imwj.miaosha: debug
    io.imwj.miaosha.dao: trace

# 自定义的redis配置
redis:
  host: 127.0.0.1
  port: 6379
  # 连接超时时间（记得添加单位，Duration）
  timeout: 3
  # 连接池最大连接数（使用负值表示没有限制） 默认 8
  poolMaxTotal: 1000
  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
  max-wait: -1ms
  # 连接池中的最大空闲连接 默认 8
  poolMaxIdle: 500
  # 连接池中的最小空闲连接 默认 0
  poolMaxWait: 500


